apiVersion: v1
kind: Service
metadata: 
  name: svc-a
  labels: 
    env: pod-svc 
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
      env: practice
      dev: tomiwa